# this is exceptions lab - 17 oct-ghadah alhrbi 




try: 
    def additoin(x, y):
        x = 10
        y = 20
        print("Addition:", x + b)


    additoin(10, 20)

except NameError:
    print("the b varible is not defined")

else: 
     print("the operation is successful")

